server {
    server_name synthnews.site www.synthnews.site;

    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;

    location / {
        proxy_pass http://127.0.0.1:3001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
    }

    listen 443 ssl;
    ssl_certificate /etc/letsencrypt/live/synthnews.site/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/synthnews.site/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
    if ($host = www.synthnews.site) {
        return 301 https://synthnews.site$request_uri;
    }
    if ($host = synthnews.site) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    server_name synthnews.site www.synthnews.site;
    return 404;
}
